wzh_ibexa_admin_location_schedules.publishLater:
  path: /wzh/ibexa/admin/content/{contentId}/publishLater/{versionNo}/{languageCode}/{locationId}
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Wizhippo\ScheduledContentBundle\Controller\ContentScheduleController::publishLater'
    languageCode: ~
    locationId: ~
  options:
    expose: true

wzh_ibexa_admin_location_schedules.hideLater:
  path: /wzh/ibexa/admin/content/{contentId}/hideLater/{versionNo}/{languageCode}/{locationId}
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Wizhippo\ScheduledContentBundle\Controller\ContentScheduleController::hideLater'
    languageCode: ~
    locationId: ~
  options:
    expose: true
